@startuml close_diagram
:Client: as Client

rectangle "BundleTracker" as BT
rectangle "BundleTrackerPrivate" as BTP
rectangle "TrackedBundle" as TB
rectangle "BundleContext" as BC
rectangle "BundleAbstractTracked" as BAT
rectangle "BundleTrackerCustomizer" as BTC

Client -> BT : 1: Close()
BT <-d- BTP : 2: Get listener and TrackedBundle
BT <-d- TB : 3: Wait for customizers
BT -> TB : 4: Close()
BT - BC : 5: Remove listener

TB -d-> BAT : 6: Untrack() on bundles
BAT -> TB : 7: CustomizerRemoved() on bundles
TB -> BTC : 8: Call user-defined RemovedBundle()

@enduml
